### ISSUE TITLE
Consider a better license or double licensing.

### ISSUE THREAD

**Issue by kromka-chleba** [davisdude/mlib#19]
Hello again,

this software was previously under the GPL which was a more preferred license for me, then it got changed to whatever this thing is. GPL is probably too strict for this library, but I believe using Apache 2.0 would be better than the current license. The current license defines terms poorly and provides no patent protection.

So consider putting this software under Apache 2.0, which is a mature permissive license:
https://www.apache.org/licenses/LICENSE-2.0.html

Perhaps double-licensing it under LGPL v3+ would also be good for those who enjoy stronger copyleft:
https://www.gnu.org/licenses/lgpl-3.0.html
This would make it easier to integrate with my GPLv3 game.

Edit: seems like Apache 2.0 is incompatible with GPLv2 so maybe it's good to keep the license as is or unify unify it with what vector2 has (see below)

**Comment by kromka-chleba** [comment]
Alternatively use the same license the Vector2 part of the code uses.
That license allows sublicensing and also doesn't have clauses preventing modification of the copyright notice so I can add my copyright to it when I modify it.

**Comment by davisdude** [comment]
Hey, sorry for the delay. Also, apologies in advance for my lack of knowledge around licensing - I'd normally much rather write code than worry about these sorts of things, so there's a lot that I'm ignorant of.

> The current license defines terms poorly and provides no patent protection.

I much prefer the simple, easy to understand licenses, personally. Which terms are unclear to you? Additionally, I don't really think patent protection is necessary, since it's just basic math, which isn't patent-able from my understanding (IANAL), 

> This would make it easier to integrate with my GPLv3 game.

[zlib is GPL-compatible.](https://www.gnu.org/licenses/license-list.html#ZLib). Additionally, it's also [GPLv3 compatible](https://www.gnu.org/licenses/quick-guide-gplv3.html#new-compatible-licenses), if I'm reading this correctly. So I don't understand what about zlib it makes it difficult to integrate.

> That license allows sublicensing and also doesn't have clauses preventing modification of the copyright notice so I can add my copyright to it when I modify it.

zlib allows for modification, so long as it is plainly marked as such. As far as changing the copyright, why would that be needed / desirable?

**Comment by kromka-chleba** [comment]
I made this issue late at night, sorry. My phrasing is probably too vague. After thinking about it all problems are purely cosmetic (keeping multiple copyright notices as separate comments in each file).

>Which terms are unclear to you?

"3. This notice may not be removed or altered from any source distribution."

"This notice" is not defined anywhere, it most likely means that comment. In that case if I modify that file, then I need add a separate notice with my own copyright that's distinct from that notice.

>So I don't understand what about zlib it makes it difficult to integrate.

If I understand the license correctly, even if I make changes under GPLv3 in the file, the original license still applies. Though I'm not sure at this point.

>zlib allows for modification, so long as it is plainly marked as such. As far as changing the copyright, why would that be needed / desirable?

Keeping information for all authors of the code at the top of the document in single place would be desirable, though after rethinking I believe I can simply put another comment with a different license into another file.

So after rethinking it pretty much boils down to a minor annoyance of keeping copyright info multiple times in the same file. I guess I can live with that, sorry for nothingburger issue.

**Comment by davisdude** [comment]
Hey no worries - I appreciate the interest! I am certainly no lawyer, nor am I tied to the zlib license, so I am open to changing it if it makes sense. Though I'd be more likely to change it to MIT, probably, if I do end up changing it. I'm going to close this for now, though feel free to re-open if it does end up being the case that zlib won't work for your needs :slightly_smiling_face:.
